
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package ParserLexer;

import java_cup.runtime.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class Parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public Parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public Parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\117\000\002\002\004\000\002\002\005\000\002\002" +
    "\004\000\002\003\004\000\002\003\003\000\002\004\003" +
    "\000\002\004\003\000\002\005\005\000\002\005\002\000" +
    "\002\006\004\000\002\006\003\000\002\007\003\000\002" +
    "\007\003\000\002\007\003\000\002\007\007\000\002\007" +
    "\007\000\002\007\005\000\002\007\004\000\002\010\005" +
    "\000\002\011\003\000\002\011\005\000\002\011\006\000" +
    "\002\013\003\000\002\013\003\000\002\013\003\000\002" +
    "\013\003\000\002\013\003\000\002\012\006\000\002\012" +
    "\011\000\002\024\010\000\002\025\002\000\002\025\003" +
    "\000\002\026\003\000\002\026\005\000\002\027\004\000" +
    "\002\014\003\000\002\014\003\000\002\014\003\000\002" +
    "\014\003\000\002\015\007\000\002\015\011\000\002\016" +
    "\007\000\002\017\013\000\002\020\011\000\002\021\004" +
    "\000\002\021\003\000\002\021\003\000\002\022\006\000" +
    "\002\022\006\000\002\023\005\000\002\030\005\000\002" +
    "\030\005\000\002\030\005\000\002\030\005\000\002\030" +
    "\005\000\002\030\005\000\002\030\005\000\002\030\005" +
    "\000\002\030\005\000\002\030\005\000\002\030\005\000" +
    "\002\030\005\000\002\030\005\000\002\030\005\000\002" +
    "\030\004\000\002\030\004\000\002\030\003\000\002\030" +
    "\003\000\002\030\003\000\002\030\003\000\002\030\003" +
    "\000\002\030\003\000\002\030\006\000\002\030\005\000" +
    "\002\046\003\000\002\046\003\000\002\046\003\000\002" +
    "\046\003\000\002\046\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\242\000\016\005\005\006\016\007\006\010\012\011" +
    "\017\055\010\001\002\000\004\002\244\001\002\000\004" +
    "\004\uffeb\001\002\000\004\004\uffe9\001\002\000\016\005" +
    "\ufffb\006\ufffb\007\ufffb\010\ufffb\011\ufffb\055\ufffb\001\002" +
    "\000\006\002\ufff9\056\117\001\002\000\004\055\241\001" +
    "\002\000\004\004\uffe7\001\002\000\016\005\ufffc\006\ufffc" +
    "\007\ufffc\010\ufffc\011\ufffc\055\ufffc\001\002\000\016\005" +
    "\005\006\016\007\006\010\012\011\017\055\ufffd\001\002" +
    "\000\004\004\020\001\002\000\004\004\uffea\001\002\000" +
    "\004\004\uffe8\001\002\000\012\017\024\060\021\062\022" +
    "\064\025\001\002\000\016\005\005\006\016\007\006\010" +
    "\012\011\017\061\uffe3\001\002\000\004\012\104\001\002" +
    "\000\042\004\uffef\005\uffef\006\uffef\007\uffef\010\uffef\011" +
    "\uffef\041\uffef\043\uffef\044\uffef\045\uffef\050\uffef\051\uffef" +
    "\053\uffef\054\uffef\055\uffef\057\uffef\001\002\000\024\004" +
    "\037\012\035\013\031\014\026\015\033\016\027\021\034" +
    "\040\036\060\032\001\002\000\042\004\uffee\005\uffee\006" +
    "\uffee\007\uffee\010\uffee\011\uffee\041\uffee\043\uffee\044\uffee" +
    "\045\uffee\050\uffee\051\uffee\053\uffee\054\uffee\055\uffee\057" +
    "\uffee\001\002\000\046\020\uffba\021\uffba\022\uffba\023\uffba" +
    "\024\uffba\025\uffba\030\uffba\031\uffba\032\uffba\033\uffba\034" +
    "\uffba\035\uffba\036\uffba\037\uffba\061\uffba\063\uffba\064\uffba" +
    "\065\uffba\001\002\000\046\020\uffbb\021\uffbb\022\uffbb\023" +
    "\uffbb\024\uffbb\025\uffbb\030\uffbb\031\uffbb\032\uffbb\033\uffbb" +
    "\034\uffbb\035\uffbb\036\uffbb\037\uffbb\061\uffbb\063\uffbb\064" +
    "\uffbb\065\uffbb\001\002\000\040\020\047\021\056\022\055" +
    "\023\051\024\044\025\045\030\050\031\042\032\054\033" +
    "\046\034\043\035\060\036\053\037\052\064\103\001\002" +
    "\000\046\020\uffbd\021\uffbd\022\uffbd\023\uffbd\024\uffbd\025" +
    "\uffbd\030\uffbd\031\uffbd\032\uffbd\033\uffbd\034\uffbd\035\uffbd" +
    "\036\uffbd\037\uffbd\061\uffbd\063\uffbd\064\uffbd\065\uffbd\001" +
    "\002\000\024\004\037\012\035\013\031\014\026\015\033" +
    "\016\027\021\034\040\036\060\032\001\002\000\046\020" +
    "\uffbc\021\uffbc\022\uffbc\023\uffbc\024\uffbc\025\uffbc\030\uffbc" +
    "\031\uffbc\032\uffbc\033\uffbc\034\uffbc\035\uffbc\036\uffbc\037" +
    "\uffbc\061\uffbc\063\uffbc\064\uffbc\065\uffbc\001\002\000\024" +
    "\004\037\012\035\013\031\014\026\015\033\016\027\021" +
    "\034\040\036\060\032\001\002\000\046\020\uffbe\021\uffbe" +
    "\022\uffbe\023\uffbe\024\uffbe\025\uffbe\030\uffbe\031\uffbe\032" +
    "\uffbe\033\uffbe\034\uffbe\035\uffbe\036\uffbe\037\uffbe\061\uffbe" +
    "\063\uffbe\064\uffbe\065\uffbe\001\002\000\024\004\037\012" +
    "\035\013\031\014\026\015\033\016\027\021\034\040\036" +
    "\060\032\001\002\000\050\020\uffbf\021\uffbf\022\uffbf\023" +
    "\uffbf\024\uffbf\025\uffbf\030\uffbf\031\uffbf\032\uffbf\033\uffbf" +
    "\034\uffbf\035\uffbf\036\uffbf\037\uffbf\061\uffbf\062\040\063" +
    "\uffbf\064\uffbf\065\uffbf\001\002\000\024\004\037\012\035" +
    "\013\031\014\026\015\033\016\027\021\034\040\036\060" +
    "\032\001\002\000\040\020\047\021\056\022\055\023\051" +
    "\024\044\025\045\030\050\031\042\032\054\033\046\034" +
    "\043\035\060\036\053\037\052\063\057\001\002\000\024" +
    "\004\037\012\035\013\031\014\026\015\033\016\027\021" +
    "\034\040\036\060\032\001\002\000\024\004\037\012\035" +
    "\013\031\014\026\015\033\016\027\021\034\040\036\060" +
    "\032\001\002\000\024\004\037\012\035\013\031\014\026" +
    "\015\033\016\027\021\034\040\036\060\032\001\002\000" +
    "\024\004\037\012\035\013\031\014\026\015\033\016\027" +
    "\021\034\040\036\060\032\001\002\000\024\004\037\012" +
    "\035\013\031\014\026\015\033\016\027\021\034\040\036" +
    "\060\032\001\002\000\024\004\037\012\035\013\031\014" +
    "\026\015\033\016\027\021\034\040\036\060\032\001\002" +
    "\000\024\004\037\012\035\013\031\014\026\015\033\016" +
    "\027\021\034\040\036\060\032\001\002\000\024\004\037" +
    "\012\035\013\031\014\026\015\033\016\027\021\034\040" +
    "\036\060\032\001\002\000\024\004\037\012\035\013\031" +
    "\014\026\015\033\016\027\021\034\040\036\060\032\001" +
    "\002\000\024\004\037\012\035\013\031\014\026\015\033" +
    "\016\027\021\034\040\036\060\032\001\002\000\024\004" +
    "\037\012\035\013\031\014\026\015\033\016\027\021\034" +
    "\040\036\060\032\001\002\000\024\004\037\012\035\013" +
    "\031\014\026\015\033\016\027\021\034\040\036\060\032" +
    "\001\002\000\024\004\037\012\035\013\031\014\026\015" +
    "\033\016\027\021\034\040\036\060\032\001\002\000\046" +
    "\020\uffb9\021\uffb9\022\uffb9\023\uffb9\024\uffb9\025\uffb9\030" +
    "\uffb9\031\uffb9\032\uffb9\033\uffb9\034\uffb9\035\uffb9\036\uffb9" +
    "\037\uffb9\061\uffb9\063\uffb9\064\uffb9\065\uffb9\001\002\000" +
    "\024\004\037\012\035\013\031\014\026\015\033\016\027" +
    "\021\034\040\036\060\032\001\002\000\046\020\uffcc\021" +
    "\uffcc\022\uffcc\023\uffcc\024\uffcc\025\uffcc\030\uffcc\031\uffcc" +
    "\032\uffcc\033\uffcc\034\uffcc\035\uffcc\036\053\037\052\061" +
    "\uffcc\063\uffcc\064\uffcc\065\uffcc\001\002\000\046\020\uffc6" +
    "\021\uffc6\022\uffc6\023\uffc6\024\uffc6\025\uffc6\030\050\031" +
    "\042\032\054\033\046\034\043\035\060\036\053\037\052" +
    "\061\uffc6\063\uffc6\064\uffc6\065\uffc6\001\002\000\046\020" +
    "\047\021\056\022\uffc4\023\uffc4\024\uffc4\025\uffc4\030\050" +
    "\031\042\032\054\033\046\034\043\035\060\036\053\037" +
    "\052\061\uffc4\063\uffc4\064\uffc4\065\uffc4\001\002\000\046" +
    "\020\uffc9\021\uffc9\022\uffc9\023\uffc9\024\uffc9\025\uffc9\030" +
    "\uffc9\031\uffc9\032\uffc9\033\uffc9\034\043\035\060\036\053" +
    "\037\052\061\uffc9\063\uffc9\064\uffc9\065\uffc9\001\002\000" +
    "\046\020\uffce\021\uffce\022\uffce\023\uffce\024\uffce\025\uffce" +
    "\030\uffce\031\uffce\032\uffce\033\uffce\034\uffce\035\uffce\036" +
    "\uffce\037\052\061\uffce\063\uffce\064\uffce\065\uffce\001\002" +
    "\000\046\020\uffcf\021\uffcf\022\uffcf\023\uffcf\024\uffcf\025" +
    "\uffcf\030\uffcf\031\uffcf\032\uffcf\033\uffcf\034\uffcf\035\uffcf" +
    "\036\uffcf\037\uffcf\061\uffcf\063\uffcf\064\uffcf\065\uffcf\001" +
    "\002\000\046\020\047\021\056\022\uffc5\023\uffc5\024\uffc5" +
    "\025\uffc5\030\050\031\042\032\054\033\046\034\043\035" +
    "\060\036\053\037\052\061\uffc5\063\uffc5\064\uffc5\065\uffc5" +
    "\001\002\000\046\020\uffcb\021\uffcb\022\uffcb\023\uffcb\024" +
    "\uffcb\025\uffcb\030\uffcb\031\uffcb\032\uffcb\033\uffcb\034\043" +
    "\035\060\036\053\037\052\061\uffcb\063\uffcb\064\uffcb\065" +
    "\uffcb\001\002\000\046\020\uffc7\021\uffc7\022\uffc7\023\uffc7" +
    "\024\uffc7\025\uffc7\030\050\031\042\032\054\033\046\034" +
    "\043\035\060\036\053\037\052\061\uffc7\063\uffc7\064\uffc7" +
    "\065\uffc7\001\002\000\046\020\uffc8\021\uffc8\022\uffc8\023" +
    "\uffc8\024\uffc8\025\uffc8\030\uffc8\031\uffc8\032\uffc8\033\uffc8" +
    "\034\043\035\060\036\053\037\052\061\uffc8\063\uffc8\064" +
    "\uffc8\065\uffc8\001\002\000\046\020\047\021\056\022\055" +
    "\023\051\024\044\025\045\030\050\031\042\032\054\033" +
    "\046\034\043\035\060\036\053\037\052\061\uffc2\063\uffc2" +
    "\064\uffc2\065\uffc2\001\002\000\046\020\047\021\056\022" +
    "\uffc3\023\uffc3\024\uffc3\025\uffc3\030\050\031\042\032\054" +
    "\033\046\034\043\035\060\036\053\037\052\061\uffc3\063" +
    "\uffc3\064\uffc3\065\uffc3\001\002\000\046\020\uffcd\021\uffcd" +
    "\022\uffcd\023\uffcd\024\uffcd\025\uffcd\030\uffcd\031\uffcd\032" +
    "\uffcd\033\uffcd\034\uffcd\035\uffcd\036\053\037\052\061\uffcd" +
    "\063\uffcd\064\uffcd\065\uffcd\001\002\000\046\020\uffca\021" +
    "\uffca\022\uffca\023\uffca\024\uffca\025\uffca\030\uffca\031\uffca" +
    "\032\uffca\033\uffca\034\043\035\060\036\053\037\052\061" +
    "\uffca\063\uffca\064\uffca\065\uffca\001\002\000\046\020\047" +
    "\021\056\022\055\023\051\024\044\025\uffc1\030\050\031" +
    "\042\032\054\033\046\034\043\035\060\036\053\037\052" +
    "\061\uffc1\063\uffc1\064\uffc1\065\uffc1\001\002\000\046\020" +
    "\uffc0\021\uffc0\022\uffc0\023\uffc0\024\uffc0\025\uffc0\030\050" +
    "\031\042\032\054\033\046\034\043\035\060\036\053\037" +
    "\052\061\uffc0\063\uffc0\064\uffc0\065\uffc0\001\002\000\040" +
    "\020\047\021\056\022\055\023\051\024\044\025\045\030" +
    "\050\031\042\032\054\033\046\034\043\035\060\036\053" +
    "\037\052\061\102\001\002\000\046\020\uffb8\021\uffb8\022" +
    "\uffb8\023\uffb8\024\uffb8\025\uffb8\030\uffb8\031\uffb8\032\uffb8" +
    "\033\uffb8\034\uffb8\035\uffb8\036\uffb8\037\uffb8\061\uffb8\063" +
    "\uffb8\064\uffb8\065\uffb8\001\002\000\042\004\uffed\005\uffed" +
    "\006\uffed\007\uffed\010\uffed\011\uffed\041\uffed\043\uffed\044" +
    "\uffed\045\uffed\050\uffed\051\uffed\053\uffed\054\uffed\055\uffed" +
    "\057\uffed\001\002\000\004\063\105\001\002\000\004\064" +
    "\106\001\002\000\042\004\uffec\005\uffec\006\uffec\007\uffec" +
    "\010\uffec\011\uffec\041\uffec\043\uffec\044\uffec\045\uffec\050" +
    "\uffec\051\uffec\053\uffec\054\uffec\055\uffec\057\uffec\001\002" +
    "\000\006\061\uffe1\065\uffe1\001\002\000\004\004\237\001" +
    "\002\000\004\061\115\001\002\000\006\061\uffe2\065\113" +
    "\001\002\000\014\005\005\006\016\007\006\010\012\011" +
    "\017\001\002\000\006\061\uffe0\065\uffe0\001\002\000\020" +
    "\005\ufff9\006\ufff9\007\ufff9\010\ufff9\011\ufff9\055\ufff9\056" +
    "\117\001\002\000\016\005\uffe4\006\uffe4\007\uffe4\010\uffe4" +
    "\011\uffe4\055\uffe4\001\002\000\036\004\141\005\005\006" +
    "\016\007\006\010\012\011\017\041\127\043\123\044\142" +
    "\045\126\050\136\051\125\053\140\054\122\001\002\000" +
    "\040\004\uffdb\005\uffdb\006\uffdb\007\uffdb\010\uffdb\011\uffdb" +
    "\041\uffdb\043\uffdb\044\uffdb\045\uffdb\050\uffdb\051\uffdb\053" +
    "\uffdb\054\uffdb\057\uffdb\001\002\000\040\004\uffdd\005\uffdd" +
    "\006\uffdd\007\uffdd\010\uffdd\011\uffdd\041\uffdd\043\uffdd\044" +
    "\uffdd\045\uffdd\050\uffdd\051\uffdd\053\uffdd\054\uffdd\057\uffdd" +
    "\001\002\000\004\060\233\001\002\000\004\060\227\001" +
    "\002\000\040\004\141\005\005\006\016\007\006\010\012" +
    "\011\017\041\127\043\123\044\142\045\126\050\136\051" +
    "\125\053\140\054\122\057\225\001\002\000\024\004\037" +
    "\012\035\013\031\014\026\015\033\016\027\021\034\040" +
    "\036\060\032\001\002\000\004\060\200\001\002\000\004" +
    "\060\172\001\002\000\040\004\ufff5\005\ufff5\006\ufff5\007" +
    "\ufff5\010\ufff5\011\ufff5\041\ufff5\043\ufff5\044\ufff5\045\ufff5" +
    "\050\ufff5\051\ufff5\053\ufff5\054\ufff5\057\ufff5\001\002\000" +
    "\004\004\171\001\002\000\040\004\uffde\005\uffde\006\uffde" +
    "\007\uffde\010\uffde\011\uffde\041\uffde\043\uffde\044\uffde\045" +
    "\uffde\050\uffde\051\uffde\053\uffde\054\uffde\057\uffde\001\002" +
    "\000\040\004\ufff6\005\ufff6\006\ufff6\007\ufff6\010\ufff6\011" +
    "\ufff6\041\ufff6\043\ufff6\044\ufff6\045\ufff6\050\ufff6\051\ufff6" +
    "\053\ufff6\054\ufff6\057\ufff6\001\002\000\040\004\ufff7\005" +
    "\ufff7\006\ufff7\007\ufff7\010\ufff7\011\ufff7\041\ufff7\043\ufff7" +
    "\044\ufff7\045\ufff7\050\ufff7\051\ufff7\053\ufff7\054\ufff7\057" +
    "\ufff7\001\002\000\040\004\ufff4\005\ufff4\006\ufff4\007\ufff4" +
    "\010\ufff4\011\ufff4\041\ufff4\043\ufff4\044\ufff4\045\ufff4\050" +
    "\ufff4\051\ufff4\053\ufff4\054\ufff4\057\ufff4\001\002\000\004" +
    "\064\170\001\002\000\040\004\uffdc\005\uffdc\006\uffdc\007" +
    "\uffdc\010\uffdc\011\uffdc\041\uffdc\043\uffdc\044\uffdc\045\uffdc" +
    "\050\uffdc\051\uffdc\053\uffdc\054\uffdc\057\uffdc\001\002\000" +
    "\004\060\164\001\002\000\006\017\154\062\153\001\002" +
    "\000\004\060\143\001\002\000\004\004\141\001\002\000" +
    "\004\065\145\001\002\000\024\004\037\012\035\013\031" +
    "\014\026\015\033\016\027\021\034\040\036\060\032\001" +
    "\002\000\040\020\047\021\056\022\055\023\051\024\044" +
    "\025\045\030\050\031\042\032\054\033\046\034\043\035" +
    "\060\036\053\037\052\065\147\001\002\000\024\004\037" +
    "\012\035\013\031\014\026\015\033\016\027\021\034\040" +
    "\036\060\032\001\002\000\040\020\047\021\056\022\055" +
    "\023\051\024\044\025\045\030\050\031\042\032\054\033" +
    "\046\034\043\035\060\036\053\037\052\061\151\001\002" +
    "\000\042\004\ufff9\005\ufff9\006\ufff9\007\ufff9\010\ufff9\011" +
    "\ufff9\041\ufff9\043\ufff9\044\ufff9\045\ufff9\050\ufff9\051\ufff9" +
    "\053\ufff9\054\ufff9\056\117\057\ufff9\001\002\000\040\004" +
    "\uffd7\005\uffd7\006\uffd7\007\uffd7\010\uffd7\011\uffd7\041\uffd7" +
    "\043\uffd7\044\uffd7\045\uffd7\050\uffd7\051\uffd7\053\uffd7\054" +
    "\uffd7\057\uffd7\001\002\000\024\004\037\012\035\013\031" +
    "\014\026\015\033\016\027\021\034\040\036\060\032\001" +
    "\002\000\024\004\037\012\035\013\031\014\026\015\033" +
    "\016\027\021\034\040\036\060\032\001\002\000\040\020" +
    "\047\021\056\022\055\023\051\024\044\025\045\030\050" +
    "\031\042\032\054\033\046\034\043\035\060\036\053\037" +
    "\052\064\156\001\002\000\042\004\uffe6\005\uffe6\006\uffe6" +
    "\007\uffe6\010\uffe6\011\uffe6\041\uffe6\043\uffe6\044\uffe6\045" +
    "\uffe6\050\uffe6\051\uffe6\053\uffe6\054\uffe6\057\uffe6\065\uffe6" +
    "\001\002\000\040\020\047\021\056\022\055\023\051\024" +
    "\044\025\045\030\050\031\042\032\054\033\046\034\043" +
    "\035\060\036\053\037\052\063\160\001\002\000\004\017" +
    "\161\001\002\000\024\004\037\012\035\013\031\014\026" +
    "\015\033\016\027\021\034\040\036\060\032\001\002\000" +
    "\040\020\047\021\056\022\055\023\051\024\044\025\045" +
    "\030\050\031\042\032\054\033\046\034\043\035\060\036" +
    "\053\037\052\064\163\001\002\000\042\004\uffe5\005\uffe5" +
    "\006\uffe5\007\uffe5\010\uffe5\011\uffe5\041\uffe5\043\uffe5\044" +
    "\uffe5\045\uffe5\050\uffe5\051\uffe5\053\uffe5\054\uffe5\057\uffe5" +
    "\065\uffe5\001\002\000\024\004\037\012\035\013\031\014" +
    "\026\015\033\016\027\021\034\040\036\060\032\001\002" +
    "\000\040\020\047\021\056\022\055\023\051\024\044\025" +
    "\045\030\050\031\042\032\054\033\046\034\043\035\060" +
    "\036\053\037\052\061\166\001\002\000\004\064\167\001" +
    "\002\000\040\004\ufff3\005\ufff3\006\ufff3\007\ufff3\010\ufff3" +
    "\011\ufff3\041\ufff3\043\ufff3\044\ufff3\045\ufff3\050\ufff3\051" +
    "\ufff3\053\ufff3\054\ufff3\057\ufff3\001\002\000\040\004\ufff0" +
    "\005\ufff0\006\ufff0\007\ufff0\010\ufff0\011\ufff0\041\ufff0\043" +
    "\ufff0\044\ufff0\045\ufff0\050\ufff0\051\ufff0\053\ufff0\054\ufff0" +
    "\057\ufff0\001\002\000\010\017\024\062\022\064\025\001" +
    "\002\000\024\004\037\012\035\013\031\014\026\015\033" +
    "\016\027\021\034\040\036\060\032\001\002\000\040\020" +
    "\047\021\056\022\055\023\051\024\044\025\045\030\050" +
    "\031\042\032\054\033\046\034\043\035\060\036\053\037" +
    "\052\061\174\001\002\000\044\004\ufff9\005\ufff9\006\ufff9" +
    "\007\ufff9\010\ufff9\011\ufff9\041\ufff9\042\ufff9\043\ufff9\044" +
    "\ufff9\045\ufff9\050\ufff9\051\ufff9\053\ufff9\054\ufff9\056\117" +
    "\057\ufff9\001\002\000\042\004\uffda\005\uffda\006\uffda\007" +
    "\uffda\010\uffda\011\uffda\041\uffda\042\176\043\uffda\044\uffda" +
    "\045\uffda\050\uffda\051\uffda\053\uffda\054\uffda\057\uffda\001" +
    "\002\000\042\004\ufff9\005\ufff9\006\ufff9\007\ufff9\010\ufff9" +
    "\011\ufff9\041\ufff9\043\ufff9\044\ufff9\045\ufff9\050\ufff9\051" +
    "\ufff9\053\ufff9\054\ufff9\056\117\057\ufff9\001\002\000\040" +
    "\004\uffd9\005\uffd9\006\uffd9\007\uffd9\010\uffd9\011\uffd9\041" +
    "\uffd9\043\uffd9\044\uffd9\045\uffd9\050\uffd9\051\uffd9\053\uffd9" +
    "\054\uffd9\057\uffd9\001\002\000\024\004\037\012\035\013" +
    "\031\014\026\015\033\016\027\021\034\040\036\060\032" +
    "\001\002\000\040\020\047\021\056\022\055\023\051\024" +
    "\044\025\045\030\050\031\042\032\054\033\046\034\043" +
    "\035\060\036\053\037\052\061\202\001\002\000\004\056" +
    "\203\001\002\000\006\046\210\047\204\001\002\000\004" +
    "\052\221\001\002\000\006\046\uffd3\057\uffd3\001\002\000" +
    "\006\046\uffd4\057\uffd4\001\002\000\006\046\210\057\217" +
    "\001\002\000\006\012\211\015\212\001\002\000\004\052" +
    "\215\001\002\000\004\052\213\001\002\000\010\046\ufff9" +
    "\056\117\057\ufff9\001\002\000\006\046\uffd1\057\uffd1\001" +
    "\002\000\010\046\ufff9\056\117\057\ufff9\001\002\000\006" +
    "\046\uffd2\057\uffd2\001\002\000\040\004\uffd6\005\uffd6\006" +
    "\uffd6\007\uffd6\010\uffd6\011\uffd6\041\uffd6\043\uffd6\044\uffd6" +
    "\045\uffd6\050\uffd6\051\uffd6\053\uffd6\054\uffd6\057\uffd6\001" +
    "\002\000\006\046\uffd5\057\uffd5\001\002\000\010\046\ufff9" +
    "\056\117\057\ufff9\001\002\000\006\046\uffd0\057\uffd0\001" +
    "\002\000\040\020\047\021\056\022\055\023\051\024\044" +
    "\025\045\030\050\031\042\032\054\033\046\034\043\035" +
    "\060\036\053\037\052\064\224\001\002\000\040\004\ufff1" +
    "\005\ufff1\006\ufff1\007\ufff1\010\ufff1\011\ufff1\041\ufff1\043" +
    "\ufff1\044\ufff1\045\ufff1\050\ufff1\051\ufff1\053\ufff1\054\ufff1" +
    "\057\ufff1\001\002\000\050\002\ufffa\004\ufffa\005\ufffa\006" +
    "\ufffa\007\ufffa\010\ufffa\011\ufffa\041\ufffa\042\ufffa\043\ufffa" +
    "\044\ufffa\045\ufffa\046\ufffa\050\ufffa\051\ufffa\053\ufffa\054" +
    "\ufffa\055\ufffa\057\ufffa\001\002\000\040\004\ufff8\005\ufff8" +
    "\006\ufff8\007\ufff8\010\ufff8\011\ufff8\041\ufff8\043\ufff8\044" +
    "\ufff8\045\ufff8\050\ufff8\051\ufff8\053\ufff8\054\ufff8\057\ufff8" +
    "\001\002\000\024\004\037\012\035\013\031\014\026\015" +
    "\033\016\027\021\034\040\036\060\032\001\002\000\040" +
    "\020\047\021\056\022\055\023\051\024\044\025\045\030" +
    "\050\031\042\032\054\033\046\034\043\035\060\036\053" +
    "\037\052\061\231\001\002\000\042\004\ufff9\005\ufff9\006" +
    "\ufff9\007\ufff9\010\ufff9\011\ufff9\041\ufff9\043\ufff9\044\ufff9" +
    "\045\ufff9\050\ufff9\051\ufff9\053\ufff9\054\ufff9\056\117\057" +
    "\ufff9\001\002\000\040\004\uffd8\005\uffd8\006\uffd8\007\uffd8" +
    "\010\uffd8\011\uffd8\041\uffd8\043\uffd8\044\uffd8\045\uffd8\050" +
    "\uffd8\051\uffd8\053\uffd8\054\uffd8\057\uffd8\001\002\000\004" +
    "\004\234\001\002\000\004\061\235\001\002\000\004\064" +
    "\236\001\002\000\040\004\ufff2\005\ufff2\006\ufff2\007\ufff2" +
    "\010\ufff2\011\ufff2\041\ufff2\043\ufff2\044\ufff2\045\ufff2\050" +
    "\ufff2\051\ufff2\053\ufff2\054\ufff2\057\ufff2\001\002\000\006" +
    "\061\uffdf\065\uffdf\001\002\000\004\055\ufffe\001\002\000" +
    "\006\002\ufff9\056\117\001\002\000\004\002\000\001\002" +
    "\000\004\002\uffff\001\002\000\004\002\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\242\000\016\002\003\003\010\004\013\010\012\013" +
    "\014\024\006\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\005\242\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\014\003\237\004\013\010\012\013\014\024\006\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\011\022\001\001\000\012\013\107\025\110\026" +
    "\111\027\106\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\030\027\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\030\100\001\001\000\002\001\001\000\004\030" +
    "\077\001\001\000\002\001\001\000\004\030\076\001\001" +
    "\000\002\001\001\000\004\030\040\001\001\000\002\001" +
    "\001\000\004\030\075\001\001\000\004\030\074\001\001" +
    "\000\004\030\073\001\001\000\004\030\072\001\001\000" +
    "\004\030\071\001\001\000\004\030\070\001\001\000\004" +
    "\030\067\001\001\000\004\030\066\001\001\000\004\030" +
    "\065\001\001\000\004\030\064\001\001\000\004\030\063" +
    "\001\001\000\004\030\062\001\001\000\004\030\061\001" +
    "\001\000\002\001\001\000\004\030\060\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\006" +
    "\013\107\027\113\001\001\000\002\001\001\000\004\005" +
    "\115\001\001\000\002\001\001\000\026\006\123\007\133" +
    "\010\132\012\127\013\130\014\134\015\131\016\120\017" +
    "\136\020\117\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\024\007\225\010" +
    "\132\012\127\013\130\014\134\015\131\016\120\017\136" +
    "\020\117\001\001\000\004\030\222\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\012" +
    "\143\001\001\000\002\001\001\000\004\030\145\001\001" +
    "\000\002\001\001\000\004\030\147\001\001\000\002\001" +
    "\001\000\004\005\151\001\001\000\002\001\001\000\004" +
    "\030\156\001\001\000\004\030\154\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\030\161\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\030\164\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\011" +
    "\022\001\001\000\004\030\172\001\001\000\002\001\001" +
    "\000\004\005\174\001\001\000\002\001\001\000\004\005" +
    "\176\001\001\000\002\001\001\000\004\030\200\001\001" +
    "\000\002\001\001\000\002\001\001\000\010\021\206\022" +
    "\205\023\204\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\022\217\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\005\213" +
    "\001\001\000\002\001\001\000\004\005\215\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\005\221\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\030\227\001\001\000\002\001\001\000\004\005\231\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\005\241\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


  /** Scan to get the next Symbol. */
  public java_cup.runtime.Symbol scan()
    throws java.lang.Exception
    {

    return s.next_token();

    }


    // declaración del scanner
    private Lexer s;
    public Parser(Lexer s) { this.s = s; } // constructor

    public void syntax_error(Symbol s) { // manejo de errores - es solo de prueba por ahora
        System.err.println("Error de sintaxis en línea " + (s.left + 1) + ", columna " + (s.right + 1));
        System.err.println("Token inesperado: " + sym.terminalNames[s.sym]);
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$Parser$actions {
  private final Parser parser;

  /** Constructor */
  CUP$Parser$actions(Parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action_part00000000(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Parser$result;

      /* select the action based on the action number */
      switch (CUP$Parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= programa EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		RESULT = start_val;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Parser$parser.done_parsing();
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // programa ::= declaracionesGlobales MAIN bloque 
            {
              Object RESULT =null;
		 System.out.println("Regla 'programa' ejecutada."); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // programa ::= MAIN bloque 
            {
              Object RESULT =null;
		 System.out.println("Regla 'programa' ejecutada."); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // declaracionesGlobales ::= globalDeclaracion declaracionesGlobales 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("declaracionesGlobales",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // declaracionesGlobales ::= globalDeclaracion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("declaracionesGlobales",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // globalDeclaracion ::= declaracion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("globalDeclaracion",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // globalDeclaracion ::= funcion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("globalDeclaracion",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // bloque ::= ABRECUENTO lista_sentencias CIERRACUENTO 
            {
              Object RESULT =null;
		 System.out.println("Regla 'bloque' ejecutada."); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("bloque",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // bloque ::= 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("bloque",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // lista_sentencias ::= lista_sentencias sentencia 
            {
              Object RESULT =null;
		 System.out.println("Regla 'lista_sentencias' procesando lista."); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_sentencias",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // lista_sentencias ::= sentencia 
            {
              Object RESULT =null;
		 System.out.println("Regla 'lista_sentencias' procesando sentencia."); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_sentencias",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // sentencia ::= declaracion 
            {
              Object RESULT =null;
		 System.out.println("Se fue por declaración"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // sentencia ::= asignacion 
            {
              Object RESULT =null;
		 System.out.println("Regla 'sentencia' ejecutó 'asignacion'."); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // sentencia ::= control_estructuras 
            {
              Object RESULT =null;
		 System.out.println("Se fue por control_estructuras"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // sentencia ::= PRINT ABREREGALO expresion CIERRAREGALO PUNTO_Y_COMA 
            {
              Object RESULT =null;
		 System.out.println("Se fue por PRINT ABREREGALO expresion CIERRAREGALO PUNTO_Y_COMA"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // sentencia ::= READ ABREREGALO IDENTIFICADOR CIERRAREGALO PUNTO_Y_COMA 
            {
              Object RESULT =null;
		 System.out.println("Se fue por READ ABREREGALO IDENTIFICADOR CIERRAREGALO PUNTO_Y_COMA"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // sentencia ::= RETURN expresion PUNTO_Y_COMA 
            {
              Object RESULT =null;
		 System.out.println("Se fue por RETURN expresion PUNTO_Y_COMA"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // sentencia ::= BREAK PUNTO_Y_COMA 
            {
              Object RESULT =null;
		 System.out.println("Se fue por BREAK PUNTO_Y_COMA"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // declaracion ::= tipo_dato IDENTIFICADOR declaracion_aux 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("declaracion",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // declaracion_aux ::= PUNTO_Y_COMA 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("declaracion_aux",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // declaracion_aux ::= ASIGNA expresion PUNTO_Y_COMA 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("declaracion_aux",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // declaracion_aux ::= ABREEMPAQUE L_INTEGER CIERRAEMPAQUE PUNTO_Y_COMA 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("declaracion_aux",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // tipo_dato ::= INTEGER 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("tipo_dato",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // tipo_dato ::= FLOAT 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("tipo_dato",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // tipo_dato ::= BOOL 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("tipo_dato",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // tipo_dato ::= CHAR 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("tipo_dato",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // tipo_dato ::= STRING 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("tipo_dato",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // asignacion ::= IDENTIFICADOR ASIGNA expresion PUNTO_Y_COMA 
            {
              Object RESULT =null;
		int idVarleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int idVarright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		Object idVar = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		
            System.out.println("Asignación detectada, variable: " + idVar.toString());
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("asignacion",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // asignacion ::= IDENTIFICADOR ABREEMPAQUE expresion CIERRAEMPAQUE ASIGNA expresion PUNTO_Y_COMA 
            {
              Object RESULT =null;
		int idVarleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)).left;
		int idVarright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)).right;
		Object idVar = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-6)).value;
		
            System.out.println("Asignación a arreglo detectada, variable: " + idVar.toString());
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("asignacion",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // funcion ::= tipo_dato IDENTIFICADOR ABREREGALO parametros CIERRAREGALO bloque 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("funcion",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // parametros ::= 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("parametros",19, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // parametros ::= lista_parametros 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("parametros",19, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // lista_parametros ::= param_dec 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_parametros",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // lista_parametros ::= lista_parametros COMA param_dec 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_parametros",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // param_dec ::= tipo_dato IDENTIFICADOR 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("param_dec",21, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // control_estructuras ::= if_estructura 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("control_estructuras",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // control_estructuras ::= while_estructura 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("control_estructuras",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // control_estructuras ::= for_estructura 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("control_estructuras",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // control_estructuras ::= switch_estructura 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("control_estructuras",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // if_estructura ::= IF ABREREGALO expresion CIERRAREGALO bloque 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("if_estructura",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // if_estructura ::= IF ABREREGALO expresion CIERRAREGALO bloque ELSE bloque 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("if_estructura",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // while_estructura ::= WHILE ABREREGALO expresion CIERRAREGALO bloque 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("while_estructura",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // for_estructura ::= FOR ABREREGALO asignacion COMA expresion COMA expresion CIERRAREGALO bloque 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("for_estructura",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-8)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // switch_estructura ::= SWITCH ABREREGALO expresion CIERRAREGALO ABRECUENTO case_blocks CIERRACUENTO 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("switch_estructura",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // case_blocks ::= case_blocks case_block 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("case_blocks",15, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // case_blocks ::= case_block 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("case_blocks",15, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // case_blocks ::= default_block 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("case_blocks",15, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // case_block ::= CASE L_INTEGER DOS_PUNTOS bloque 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("case_block",16, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // case_block ::= CASE CHAR_LITERAL DOS_PUNTOS bloque 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("case_block",16, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // default_block ::= DEFAULT DOS_PUNTOS bloque 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("default_block",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // expresion ::= expresion DISYUNCION expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // expresion ::= expresion CONJUNCION expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // expresion ::= expresion IGUALDAD expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // expresion ::= expresion DIFERENTE expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // expresion ::= expresion MENOR expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // expresion ::= expresion MENOROIGUAL expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // expresion ::= expresion MAYOR expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // expresion ::= expresion MAYOROIGUAL expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // expresion ::= expresion SUMA expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // expresion ::= expresion RESTA expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // expresion ::= expresion MULTIPLICACION expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // expresion ::= expresion DIVISION expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // expresion ::= expresion MODULE expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // expresion ::= expresion POTENCIA expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // expresion ::= NEGACION expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // expresion ::= RESTA expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // expresion ::= IDENTIFICADOR 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // expresion ::= L_INTEGER 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // expresion ::= FLOAT_LITERAL 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // expresion ::= CHAR_LITERAL 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // expresion ::= STRING_LITERAL 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 71: // expresion ::= BOOL_LITERAL 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 72: // expresion ::= IDENTIFICADOR ABREEMPAQUE expresion CIERRAEMPAQUE 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 73: // expresion ::= ABREREGALO expresion CIERRAREGALO 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 74: // literal ::= L_INTEGER 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("literal",36, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 75: // literal ::= FLOAT_LITERAL 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("literal",36, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 76: // literal ::= CHAR_LITERAL 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("literal",36, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 77: // literal ::= STRING_LITERAL 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("literal",36, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 78: // literal ::= BOOL_LITERAL 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("literal",36, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$Parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
              return CUP$Parser$do_action_part00000000(
                               CUP$Parser$act_num,
                               CUP$Parser$parser,
                               CUP$Parser$stack,
                               CUP$Parser$top);
    }
}

}
