
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package ParserLexer;

import java_cup.runtime.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class Parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public Parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public Parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\122\000\002\002\004\000\002\002\005\000\002\002" +
    "\004\000\002\003\004\000\002\003\003\000\002\004\003" +
    "\000\002\004\003\000\002\005\005\000\002\005\002\000" +
    "\002\005\004\000\002\006\004\000\002\006\003\000\002" +
    "\006\004\000\002\007\003\000\002\007\003\000\002\007" +
    "\003\000\002\007\007\000\002\007\007\000\002\007\005" +
    "\000\002\007\004\000\002\007\003\000\002\010\005\000" +
    "\002\011\003\000\002\011\005\000\002\011\006\000\002" +
    "\013\003\000\002\013\003\000\002\013\003\000\002\013" +
    "\003\000\002\013\003\000\002\012\006\000\002\012\011" +
    "\000\002\024\010\000\002\025\002\000\002\025\003\000" +
    "\002\026\003\000\002\026\005\000\002\027\004\000\002" +
    "\014\003\000\002\014\003\000\002\014\003\000\002\014" +
    "\003\000\002\015\007\000\002\015\011\000\002\016\007" +
    "\000\002\017\013\000\002\020\011\000\002\021\004\000" +
    "\002\021\003\000\002\021\003\000\002\022\006\000\002" +
    "\022\006\000\002\023\005\000\002\030\005\000\002\030" +
    "\005\000\002\030\005\000\002\030\005\000\002\030\005" +
    "\000\002\030\005\000\002\030\005\000\002\030\005\000" +
    "\002\030\005\000\002\030\005\000\002\030\005\000\002" +
    "\030\005\000\002\030\005\000\002\030\005\000\002\030" +
    "\004\000\002\030\004\000\002\030\004\000\002\030\004" +
    "\000\002\030\004\000\002\030\004\000\002\030\003\000" +
    "\002\030\003\000\002\030\003\000\002\030\003\000\002" +
    "\030\003\000\002\030\003\000\002\030\006\000\002\030" +
    "\005\000\002\030\004" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\257\000\016\005\005\006\016\007\006\010\012\011" +
    "\017\056\010\001\002\000\004\002\261\001\002\000\004" +
    "\004\uffe8\001\002\000\004\004\uffe6\001\002\000\016\005" +
    "\ufffb\006\ufffb\007\ufffb\010\ufffb\011\ufffb\056\ufffb\001\002" +
    "\000\010\002\ufff9\003\126\057\130\001\002\000\016\005" +
    "\005\006\016\007\006\010\012\011\017\056\255\001\002" +
    "\000\004\004\uffe4\001\002\000\016\005\ufffc\006\ufffc\007" +
    "\ufffc\010\ufffc\011\ufffc\056\ufffc\001\002\000\016\005\ufffd" +
    "\006\ufffd\007\ufffd\010\ufffd\011\ufffd\056\ufffd\001\002\000" +
    "\004\004\020\001\002\000\004\004\uffe7\001\002\000\004" +
    "\004\uffe5\001\002\000\012\017\025\061\021\063\022\065" +
    "\024\001\002\000\016\005\005\006\016\007\006\010\012" +
    "\011\017\062\uffe0\001\002\000\004\012\114\001\002\000" +
    "\044\004\uffec\005\uffec\006\uffec\007\uffec\010\uffec\011\uffec" +
    "\022\uffec\042\uffec\044\uffec\045\uffec\046\uffec\051\uffec\052" +
    "\uffec\054\uffec\055\uffec\056\uffec\060\uffec\001\002\000\044" +
    "\004\uffeb\005\uffeb\006\uffeb\007\uffeb\010\uffeb\011\uffeb\022" +
    "\uffeb\042\uffeb\044\uffeb\045\uffeb\046\uffeb\051\uffeb\052\uffeb" +
    "\054\uffeb\055\uffeb\056\uffeb\060\uffeb\001\002\000\032\003" +
    "\031\004\042\012\040\013\032\014\026\015\035\016\027" +
    "\020\034\021\036\024\037\041\041\061\033\001\002\000" +
    "\046\023\uffb3\024\uffb3\025\uffb3\026\uffb3\027\uffb3\030\uffb3" +
    "\031\uffb3\032\uffb3\033\uffb3\034\uffb3\035\uffb3\036\uffb3\037" +
    "\uffb3\040\uffb3\062\uffb3\064\uffb3\065\uffb3\066\uffb3\001\002" +
    "\000\046\023\uffb4\024\uffb4\025\uffb4\026\uffb4\027\uffb4\030" +
    "\uffb4\031\uffb4\032\uffb4\033\uffb4\034\uffb4\035\uffb4\036\uffb4" +
    "\037\uffb4\040\uffb4\062\uffb4\064\uffb4\065\uffb4\066\uffb4\001" +
    "\002\000\040\023\054\024\063\025\062\026\056\027\051" +
    "\030\052\031\055\032\047\033\061\034\053\035\050\036" +
    "\064\037\060\040\057\065\113\001\002\000\004\062\112" +
    "\001\002\000\046\023\uffb6\024\uffb6\025\uffb6\026\uffb6\027" +
    "\uffb6\030\uffb6\031\uffb6\032\uffb6\033\uffb6\034\uffb6\035\uffb6" +
    "\036\uffb6\037\uffb6\040\uffb6\062\uffb6\064\uffb6\065\uffb6\066" +
    "\uffb6\001\002\000\032\003\031\004\042\012\040\013\032" +
    "\014\026\015\035\016\027\020\034\021\036\024\037\041" +
    "\041\061\033\001\002\000\004\004\107\001\002\000\046" +
    "\023\uffb5\024\uffb5\025\uffb5\026\uffb5\027\uffb5\030\uffb5\031" +
    "\uffb5\032\uffb5\033\uffb5\034\uffb5\035\uffb5\036\uffb5\037\uffb5" +
    "\040\uffb5\062\uffb5\064\uffb5\065\uffb5\066\uffb5\001\002\000" +
    "\004\004\106\001\002\000\032\003\031\004\042\012\040" +
    "\013\032\014\026\015\035\016\027\020\034\021\036\024" +
    "\037\041\041\061\033\001\002\000\046\023\uffb7\024\uffb7" +
    "\025\uffb7\026\uffb7\027\uffb7\030\uffb7\031\uffb7\032\uffb7\033" +
    "\uffb7\034\uffb7\035\uffb7\036\uffb7\037\uffb7\040\uffb7\062\uffb7" +
    "\064\uffb7\065\uffb7\066\uffb7\001\002\000\032\003\031\004" +
    "\042\012\040\013\032\014\026\015\035\016\027\020\034" +
    "\021\036\024\037\041\041\061\033\001\002\000\054\020" +
    "\045\021\043\023\uffb8\024\uffb8\025\uffb8\026\uffb8\027\uffb8" +
    "\030\uffb8\031\uffb8\032\uffb8\033\uffb8\034\uffb8\035\uffb8\036" +
    "\uffb8\037\uffb8\040\uffb8\062\uffb8\063\044\064\uffb8\065\uffb8" +
    "\066\uffb8\001\002\000\046\023\uffb9\024\uffb9\025\uffb9\026" +
    "\uffb9\027\uffb9\030\uffb9\031\uffb9\032\uffb9\033\uffb9\034\uffb9" +
    "\035\uffb9\036\uffb9\037\uffb9\040\uffb9\062\uffb9\064\uffb9\065" +
    "\uffb9\066\uffb9\001\002\000\032\003\031\004\042\012\040" +
    "\013\032\014\026\015\035\016\027\020\034\021\036\024" +
    "\037\041\041\061\033\001\002\000\046\023\uffba\024\uffba" +
    "\025\uffba\026\uffba\027\uffba\030\uffba\031\uffba\032\uffba\033" +
    "\uffba\034\uffba\035\uffba\036\uffba\037\uffba\040\uffba\062\uffba" +
    "\064\uffba\065\uffba\066\uffba\001\002\000\040\023\054\024" +
    "\063\025\062\026\056\027\051\030\052\031\055\032\047" +
    "\033\061\034\053\035\050\036\064\037\060\040\057\064" +
    "\065\001\002\000\032\003\031\004\042\012\040\013\032" +
    "\014\026\015\035\016\027\020\034\021\036\024\037\041" +
    "\041\061\033\001\002\000\032\003\031\004\042\012\040" +
    "\013\032\014\026\015\035\016\027\020\034\021\036\024" +
    "\037\041\041\061\033\001\002\000\032\003\031\004\042" +
    "\012\040\013\032\014\026\015\035\016\027\020\034\021" +
    "\036\024\037\041\041\061\033\001\002\000\032\003\031" +
    "\004\042\012\040\013\032\014\026\015\035\016\027\020" +
    "\034\021\036\024\037\041\041\061\033\001\002\000\032" +
    "\003\031\004\042\012\040\013\032\014\026\015\035\016" +
    "\027\020\034\021\036\024\037\041\041\061\033\001\002" +
    "\000\032\003\031\004\042\012\040\013\032\014\026\015" +
    "\035\016\027\020\034\021\036\024\037\041\041\061\033" +
    "\001\002\000\032\003\031\004\042\012\040\013\032\014" +
    "\026\015\035\016\027\020\034\021\036\024\037\041\041" +
    "\061\033\001\002\000\032\003\031\004\042\012\040\013" +
    "\032\014\026\015\035\016\027\020\034\021\036\024\037" +
    "\041\041\061\033\001\002\000\032\003\031\004\042\012" +
    "\040\013\032\014\026\015\035\016\027\020\034\021\036" +
    "\024\037\041\041\061\033\001\002\000\032\003\031\004" +
    "\042\012\040\013\032\014\026\015\035\016\027\020\034" +
    "\021\036\024\037\041\041\061\033\001\002\000\032\003" +
    "\031\004\042\012\040\013\032\014\026\015\035\016\027" +
    "\020\034\021\036\024\037\041\041\061\033\001\002\000" +
    "\032\003\031\004\042\012\040\013\032\014\026\015\035" +
    "\016\027\020\034\021\036\024\037\041\041\061\033\001" +
    "\002\000\032\003\031\004\042\012\040\013\032\014\026" +
    "\015\035\016\027\020\034\021\036\024\037\041\041\061" +
    "\033\001\002\000\032\003\031\004\042\012\040\013\032" +
    "\014\026\015\035\016\027\020\034\021\036\024\037\041" +
    "\041\061\033\001\002\000\046\023\uffb2\024\uffb2\025\uffb2" +
    "\026\uffb2\027\uffb2\030\uffb2\031\uffb2\032\uffb2\033\uffb2\034" +
    "\uffb2\035\uffb2\036\uffb2\037\uffb2\040\uffb2\062\uffb2\064\uffb2" +
    "\065\uffb2\066\uffb2\001\002\000\046\023\uffc9\024\uffc9\025" +
    "\uffc9\026\uffc9\027\uffc9\030\uffc9\031\uffc9\032\uffc9\033\uffc9" +
    "\034\uffc9\035\uffc9\036\uffc9\037\060\040\057\062\uffc9\064" +
    "\uffc9\065\uffc9\066\uffc9\001\002\000\046\023\uffc3\024\uffc3" +
    "\025\uffc3\026\uffc3\027\uffc3\030\uffc3\031\055\032\047\033" +
    "\061\034\053\035\050\036\064\037\060\040\057\062\uffc3" +
    "\064\uffc3\065\uffc3\066\uffc3\001\002\000\046\023\054\024" +
    "\063\025\uffc1\026\uffc1\027\uffc1\030\uffc1\031\055\032\047" +
    "\033\061\034\053\035\050\036\064\037\060\040\057\062" +
    "\uffc1\064\uffc1\065\uffc1\066\uffc1\001\002\000\046\023\uffc6" +
    "\024\uffc6\025\uffc6\026\uffc6\027\uffc6\030\uffc6\031\uffc6\032" +
    "\uffc6\033\uffc6\034\uffc6\035\050\036\064\037\060\040\057" +
    "\062\uffc6\064\uffc6\065\uffc6\066\uffc6\001\002\000\046\023" +
    "\uffcb\024\uffcb\025\uffcb\026\uffcb\027\uffcb\030\uffcb\031\uffcb" +
    "\032\uffcb\033\uffcb\034\uffcb\035\uffcb\036\uffcb\037\uffcb\040" +
    "\057\062\uffcb\064\uffcb\065\uffcb\066\uffcb\001\002\000\046" +
    "\023\uffcc\024\uffcc\025\uffcc\026\uffcc\027\uffcc\030\uffcc\031" +
    "\uffcc\032\uffcc\033\uffcc\034\uffcc\035\uffcc\036\uffcc\037\uffcc" +
    "\040\uffcc\062\uffcc\064\uffcc\065\uffcc\066\uffcc\001\002\000" +
    "\046\023\054\024\063\025\uffc2\026\uffc2\027\uffc2\030\uffc2" +
    "\031\055\032\047\033\061\034\053\035\050\036\064\037" +
    "\060\040\057\062\uffc2\064\uffc2\065\uffc2\066\uffc2\001\002" +
    "\000\046\023\uffc8\024\uffc8\025\uffc8\026\uffc8\027\uffc8\030" +
    "\uffc8\031\uffc8\032\uffc8\033\uffc8\034\uffc8\035\050\036\064" +
    "\037\060\040\057\062\uffc8\064\uffc8\065\uffc8\066\uffc8\001" +
    "\002\000\046\023\uffc4\024\uffc4\025\uffc4\026\uffc4\027\uffc4" +
    "\030\uffc4\031\055\032\047\033\061\034\053\035\050\036" +
    "\064\037\060\040\057\062\uffc4\064\uffc4\065\uffc4\066\uffc4" +
    "\001\002\000\046\023\uffc5\024\uffc5\025\uffc5\026\uffc5\027" +
    "\uffc5\030\uffc5\031\uffc5\032\uffc5\033\uffc5\034\uffc5\035\050" +
    "\036\064\037\060\040\057\062\uffc5\064\uffc5\065\uffc5\066" +
    "\uffc5\001\002\000\046\023\054\024\063\025\062\026\056" +
    "\027\051\030\052\031\055\032\047\033\061\034\053\035" +
    "\050\036\064\037\060\040\057\062\uffbf\064\uffbf\065\uffbf" +
    "\066\uffbf\001\002\000\046\023\054\024\063\025\uffc0\026" +
    "\uffc0\027\uffc0\030\uffc0\031\055\032\047\033\061\034\053" +
    "\035\050\036\064\037\060\040\057\062\uffc0\064\uffc0\065" +
    "\uffc0\066\uffc0\001\002\000\046\023\uffca\024\uffca\025\uffca" +
    "\026\uffca\027\uffca\030\uffca\031\uffca\032\uffca\033\uffca\034" +
    "\uffca\035\uffca\036\uffca\037\060\040\057\062\uffca\064\uffca" +
    "\065\uffca\066\uffca\001\002\000\046\023\uffc7\024\uffc7\025" +
    "\uffc7\026\uffc7\027\uffc7\030\uffc7\031\uffc7\032\uffc7\033\uffc7" +
    "\034\uffc7\035\050\036\064\037\060\040\057\062\uffc7\064" +
    "\uffc7\065\uffc7\066\uffc7\001\002\000\046\023\054\024\063" +
    "\025\062\026\056\027\051\030\uffbe\031\055\032\047\033" +
    "\061\034\053\035\050\036\064\037\060\040\057\062\uffbe" +
    "\064\uffbe\065\uffbe\066\uffbe\001\002\000\046\023\uffbd\024" +
    "\uffbd\025\uffbd\026\uffbd\027\uffbd\030\uffbd\031\055\032\047" +
    "\033\061\034\053\035\050\036\064\037\060\040\057\062" +
    "\uffbd\064\uffbd\065\uffbd\066\uffbd\001\002\000\046\023\uffbb" +
    "\024\uffbb\025\uffbb\026\uffbb\027\uffbb\030\uffbb\031\uffbb\032" +
    "\uffbb\033\uffbb\034\uffbb\035\uffbb\036\uffbb\037\uffbb\040\uffbb" +
    "\062\uffbb\064\uffbb\065\uffbb\066\uffbb\001\002\000\046\023" +
    "\uffbc\024\uffbc\025\uffbc\026\uffbc\027\uffbc\030\uffbc\031\uffbc" +
    "\032\uffbc\033\uffbc\034\uffbc\035\uffbc\036\uffbc\037\uffbc\040" +
    "\uffbc\062\uffbc\064\uffbc\065\uffbc\066\uffbc\001\002\000\040" +
    "\023\054\024\063\025\062\026\056\027\051\030\052\031" +
    "\055\032\047\033\061\034\053\035\050\036\064\037\060" +
    "\040\057\062\111\001\002\000\046\023\uffb1\024\uffb1\025" +
    "\uffb1\026\uffb1\027\uffb1\030\uffb1\031\uffb1\032\uffb1\033\uffb1" +
    "\034\uffb1\035\uffb1\036\uffb1\037\uffb1\040\uffb1\062\uffb1\064" +
    "\uffb1\065\uffb1\066\uffb1\001\002\000\046\023\uffb0\024\uffb0" +
    "\025\uffb0\026\uffb0\027\uffb0\030\uffb0\031\uffb0\032\uffb0\033" +
    "\uffb0\034\uffb0\035\uffb0\036\uffb0\037\uffb0\040\uffb0\062\uffb0" +
    "\064\uffb0\065\uffb0\066\uffb0\001\002\000\044\004\uffea\005" +
    "\uffea\006\uffea\007\uffea\010\uffea\011\uffea\022\uffea\042\uffea" +
    "\044\uffea\045\uffea\046\uffea\051\uffea\052\uffea\054\uffea\055" +
    "\uffea\056\uffea\060\uffea\001\002\000\004\064\115\001\002" +
    "\000\004\065\116\001\002\000\044\004\uffe9\005\uffe9\006" +
    "\uffe9\007\uffe9\010\uffe9\011\uffe9\022\uffe9\042\uffe9\044\uffe9" +
    "\045\uffe9\046\uffe9\051\uffe9\052\uffe9\054\uffe9\055\uffe9\056" +
    "\uffe9\060\uffe9\001\002\000\006\062\uffde\066\uffde\001\002" +
    "\000\004\004\254\001\002\000\004\062\125\001\002\000" +
    "\006\062\uffdf\066\123\001\002\000\014\005\005\006\016" +
    "\007\006\010\012\011\017\001\002\000\006\062\uffdd\066" +
    "\uffdd\001\002\000\022\003\126\005\ufff9\006\ufff9\007\ufff9" +
    "\010\ufff9\011\ufff9\056\ufff9\057\130\001\002\000\004\060" +
    "\253\001\002\000\016\005\uffe1\006\uffe1\007\uffe1\010\uffe1" +
    "\011\uffe1\056\uffe1\001\002\000\042\003\152\004\154\005" +
    "\005\006\016\007\006\010\012\011\017\022\150\042\140" +
    "\044\134\045\155\046\137\051\147\052\136\054\153\055" +
    "\133\001\002\000\042\004\uffd8\005\uffd8\006\uffd8\007\uffd8" +
    "\010\uffd8\011\uffd8\022\uffd8\042\uffd8\044\uffd8\045\uffd8\046" +
    "\uffd8\051\uffd8\052\uffd8\054\uffd8\055\uffd8\060\uffd8\001\002" +
    "\000\042\004\uffda\005\uffda\006\uffda\007\uffda\010\uffda\011" +
    "\uffda\022\uffda\042\uffda\044\uffda\045\uffda\046\uffda\051\uffda" +
    "\052\uffda\054\uffda\055\uffda\060\uffda\001\002\000\004\061" +
    "\247\001\002\000\004\061\243\001\002\000\042\004\154" +
    "\005\005\006\016\007\006\010\012\011\017\022\150\042" +
    "\140\044\134\045\155\046\137\051\147\052\136\054\153" +
    "\055\133\060\241\001\002\000\032\003\031\004\042\012" +
    "\040\013\032\014\026\015\035\016\027\020\034\021\036" +
    "\024\037\041\041\061\033\001\002\000\004\061\214\001" +
    "\002\000\004\061\206\001\002\000\042\004\ufff3\005\ufff3" +
    "\006\ufff3\007\ufff3\010\ufff3\011\ufff3\022\ufff3\042\ufff3\044" +
    "\ufff3\045\ufff3\046\ufff3\051\ufff3\052\ufff3\054\ufff3\055\ufff3" +
    "\060\ufff3\001\002\000\004\004\205\001\002\000\042\004" +
    "\uffdb\005\uffdb\006\uffdb\007\uffdb\010\uffdb\011\uffdb\022\uffdb" +
    "\042\uffdb\044\uffdb\045\uffdb\046\uffdb\051\uffdb\052\uffdb\054" +
    "\uffdb\055\uffdb\060\uffdb\001\002\000\042\004\ufff4\005\ufff4" +
    "\006\ufff4\007\ufff4\010\ufff4\011\ufff4\022\ufff4\042\ufff4\044" +
    "\ufff4\045\ufff4\046\ufff4\051\ufff4\052\ufff4\054\ufff4\055\ufff4" +
    "\060\ufff4\001\002\000\042\004\ufff6\005\ufff6\006\ufff6\007" +
    "\ufff6\010\ufff6\011\ufff6\022\ufff6\042\ufff6\044\ufff6\045\ufff6" +
    "\046\ufff6\051\ufff6\052\ufff6\054\ufff6\055\ufff6\060\ufff6\001" +
    "\002\000\042\004\ufff2\005\ufff2\006\ufff2\007\ufff2\010\ufff2" +
    "\011\ufff2\022\ufff2\042\ufff2\044\ufff2\045\ufff2\046\ufff2\051" +
    "\ufff2\052\ufff2\054\ufff2\055\ufff2\060\ufff2\001\002\000\004" +
    "\065\204\001\002\000\042\004\uffed\005\uffed\006\uffed\007" +
    "\uffed\010\uffed\011\uffed\022\uffed\042\uffed\044\uffed\045\uffed" +
    "\046\uffed\051\uffed\052\uffed\054\uffed\055\uffed\060\uffed\001" +
    "\002\000\042\004\uffd9\005\uffd9\006\uffd9\007\uffd9\010\uffd9" +
    "\011\uffd9\022\uffd9\042\uffd9\044\uffd9\045\uffd9\046\uffd9\051" +
    "\uffd9\052\uffd9\054\uffd9\055\uffd9\060\uffd9\001\002\000\004" +
    "\065\203\001\002\000\004\061\177\001\002\000\006\017" +
    "\167\063\166\001\002\000\004\061\156\001\002\000\004" +
    "\004\154\001\002\000\004\066\160\001\002\000\032\003" +
    "\031\004\042\012\040\013\032\014\026\015\035\016\027" +
    "\020\034\021\036\024\037\041\041\061\033\001\002\000" +
    "\040\023\054\024\063\025\062\026\056\027\051\030\052" +
    "\031\055\032\047\033\061\034\053\035\050\036\064\037" +
    "\060\040\057\066\162\001\002\000\032\003\031\004\042" +
    "\012\040\013\032\014\026\015\035\016\027\020\034\021" +
    "\036\024\037\041\041\061\033\001\002\000\040\023\054" +
    "\024\063\025\062\026\056\027\051\030\052\031\055\032" +
    "\047\033\061\034\053\035\050\036\064\037\060\040\057" +
    "\062\164\001\002\000\046\003\126\004\ufff9\005\ufff9\006" +
    "\ufff9\007\ufff9\010\ufff9\011\ufff9\022\ufff9\042\ufff9\044\ufff9" +
    "\045\ufff9\046\ufff9\051\ufff9\052\ufff9\054\ufff9\055\ufff9\057" +
    "\130\060\ufff9\001\002\000\042\004\uffd4\005\uffd4\006\uffd4" +
    "\007\uffd4\010\uffd4\011\uffd4\022\uffd4\042\uffd4\044\uffd4\045" +
    "\uffd4\046\uffd4\051\uffd4\052\uffd4\054\uffd4\055\uffd4\060\uffd4" +
    "\001\002\000\032\003\031\004\042\012\040\013\032\014" +
    "\026\015\035\016\027\020\034\021\036\024\037\041\041" +
    "\061\033\001\002\000\032\003\031\004\042\012\040\013" +
    "\032\014\026\015\035\016\027\020\034\021\036\024\037" +
    "\041\041\061\033\001\002\000\040\023\054\024\063\025" +
    "\062\026\056\027\051\030\052\031\055\032\047\033\061" +
    "\034\053\035\050\036\064\037\060\040\057\065\171\001" +
    "\002\000\044\004\uffe3\005\uffe3\006\uffe3\007\uffe3\010\uffe3" +
    "\011\uffe3\022\uffe3\042\uffe3\044\uffe3\045\uffe3\046\uffe3\051" +
    "\uffe3\052\uffe3\054\uffe3\055\uffe3\060\uffe3\066\uffe3\001\002" +
    "\000\040\023\054\024\063\025\062\026\056\027\051\030" +
    "\052\031\055\032\047\033\061\034\053\035\050\036\064" +
    "\037\060\040\057\064\173\001\002\000\004\017\174\001" +
    "\002\000\032\003\031\004\042\012\040\013\032\014\026" +
    "\015\035\016\027\020\034\021\036\024\037\041\041\061" +
    "\033\001\002\000\040\023\054\024\063\025\062\026\056" +
    "\027\051\030\052\031\055\032\047\033\061\034\053\035" +
    "\050\036\064\037\060\040\057\065\176\001\002\000\044" +
    "\004\uffe2\005\uffe2\006\uffe2\007\uffe2\010\uffe2\011\uffe2\022" +
    "\uffe2\042\uffe2\044\uffe2\045\uffe2\046\uffe2\051\uffe2\052\uffe2" +
    "\054\uffe2\055\uffe2\060\uffe2\066\uffe2\001\002\000\032\003" +
    "\031\004\042\012\040\013\032\014\026\015\035\016\027" +
    "\020\034\021\036\024\037\041\041\061\033\001\002\000" +
    "\040\023\054\024\063\025\062\026\056\027\051\030\052" +
    "\031\055\032\047\033\061\034\053\035\050\036\064\037" +
    "\060\040\057\062\201\001\002\000\004\065\202\001\002" +
    "\000\042\004\ufff1\005\ufff1\006\ufff1\007\ufff1\010\ufff1\011" +
    "\ufff1\022\ufff1\042\ufff1\044\ufff1\045\ufff1\046\ufff1\051\ufff1" +
    "\052\ufff1\054\ufff1\055\ufff1\060\ufff1\001\002\000\042\004" +
    "\ufff5\005\ufff5\006\ufff5\007\ufff5\010\ufff5\011\ufff5\022\ufff5" +
    "\042\ufff5\044\ufff5\045\ufff5\046\ufff5\051\ufff5\052\ufff5\054" +
    "\ufff5\055\ufff5\060\ufff5\001\002\000\042\004\uffee\005\uffee" +
    "\006\uffee\007\uffee\010\uffee\011\uffee\022\uffee\042\uffee\044" +
    "\uffee\045\uffee\046\uffee\051\uffee\052\uffee\054\uffee\055\uffee" +
    "\060\uffee\001\002\000\010\017\025\063\022\065\024\001" +
    "\002\000\032\003\031\004\042\012\040\013\032\014\026" +
    "\015\035\016\027\020\034\021\036\024\037\041\041\061" +
    "\033\001\002\000\040\023\054\024\063\025\062\026\056" +
    "\027\051\030\052\031\055\032\047\033\061\034\053\035" +
    "\050\036\064\037\060\040\057\062\210\001\002\000\050" +
    "\003\126\004\ufff9\005\ufff9\006\ufff9\007\ufff9\010\ufff9\011" +
    "\ufff9\022\ufff9\042\ufff9\043\ufff9\044\ufff9\045\ufff9\046\ufff9" +
    "\051\ufff9\052\ufff9\054\ufff9\055\ufff9\057\130\060\ufff9\001" +
    "\002\000\044\004\uffd7\005\uffd7\006\uffd7\007\uffd7\010\uffd7" +
    "\011\uffd7\022\uffd7\042\uffd7\043\212\044\uffd7\045\uffd7\046" +
    "\uffd7\051\uffd7\052\uffd7\054\uffd7\055\uffd7\060\uffd7\001\002" +
    "\000\046\003\126\004\ufff9\005\ufff9\006\ufff9\007\ufff9\010" +
    "\ufff9\011\ufff9\022\ufff9\042\ufff9\044\ufff9\045\ufff9\046\ufff9" +
    "\051\ufff9\052\ufff9\054\ufff9\055\ufff9\057\130\060\ufff9\001" +
    "\002\000\042\004\uffd6\005\uffd6\006\uffd6\007\uffd6\010\uffd6" +
    "\011\uffd6\022\uffd6\042\uffd6\044\uffd6\045\uffd6\046\uffd6\051" +
    "\uffd6\052\uffd6\054\uffd6\055\uffd6\060\uffd6\001\002\000\032" +
    "\003\031\004\042\012\040\013\032\014\026\015\035\016" +
    "\027\020\034\021\036\024\037\041\041\061\033\001\002" +
    "\000\040\023\054\024\063\025\062\026\056\027\051\030" +
    "\052\031\055\032\047\033\061\034\053\035\050\036\064" +
    "\037\060\040\057\062\216\001\002\000\004\057\217\001" +
    "\002\000\006\047\224\050\220\001\002\000\004\053\235" +
    "\001\002\000\006\047\uffd0\060\uffd0\001\002\000\006\047" +
    "\uffd1\060\uffd1\001\002\000\006\047\224\060\233\001\002" +
    "\000\006\012\225\015\226\001\002\000\004\053\231\001" +
    "\002\000\004\053\227\001\002\000\012\003\126\047\ufff9" +
    "\057\130\060\ufff9\001\002\000\006\047\uffce\060\uffce\001" +
    "\002\000\012\003\126\047\ufff9\057\130\060\ufff9\001\002" +
    "\000\006\047\uffcf\060\uffcf\001\002\000\042\004\uffd3\005" +
    "\uffd3\006\uffd3\007\uffd3\010\uffd3\011\uffd3\022\uffd3\042\uffd3" +
    "\044\uffd3\045\uffd3\046\uffd3\051\uffd3\052\uffd3\054\uffd3\055" +
    "\uffd3\060\uffd3\001\002\000\006\047\uffd2\060\uffd2\001\002" +
    "\000\012\003\126\047\ufff9\057\130\060\ufff9\001\002\000" +
    "\006\047\uffcd\060\uffcd\001\002\000\040\023\054\024\063" +
    "\025\062\026\056\027\051\030\052\031\055\032\047\033" +
    "\061\034\053\035\050\036\064\037\060\040\057\065\240" +
    "\001\002\000\042\004\uffef\005\uffef\006\uffef\007\uffef\010" +
    "\uffef\011\uffef\022\uffef\042\uffef\044\uffef\045\uffef\046\uffef" +
    "\051\uffef\052\uffef\054\uffef\055\uffef\060\uffef\001\002\000" +
    "\052\002\ufffa\004\ufffa\005\ufffa\006\ufffa\007\ufffa\010\ufffa" +
    "\011\ufffa\022\ufffa\042\ufffa\043\ufffa\044\ufffa\045\ufffa\046" +
    "\ufffa\047\ufffa\051\ufffa\052\ufffa\054\ufffa\055\ufffa\056\ufffa" +
    "\060\ufffa\001\002\000\042\004\ufff7\005\ufff7\006\ufff7\007" +
    "\ufff7\010\ufff7\011\ufff7\022\ufff7\042\ufff7\044\ufff7\045\ufff7" +
    "\046\ufff7\051\ufff7\052\ufff7\054\ufff7\055\ufff7\060\ufff7\001" +
    "\002\000\032\003\031\004\042\012\040\013\032\014\026" +
    "\015\035\016\027\020\034\021\036\024\037\041\041\061" +
    "\033\001\002\000\040\023\054\024\063\025\062\026\056" +
    "\027\051\030\052\031\055\032\047\033\061\034\053\035" +
    "\050\036\064\037\060\040\057\062\245\001\002\000\046" +
    "\003\126\004\ufff9\005\ufff9\006\ufff9\007\ufff9\010\ufff9\011" +
    "\ufff9\022\ufff9\042\ufff9\044\ufff9\045\ufff9\046\ufff9\051\ufff9" +
    "\052\ufff9\054\ufff9\055\ufff9\057\130\060\ufff9\001\002\000" +
    "\042\004\uffd5\005\uffd5\006\uffd5\007\uffd5\010\uffd5\011\uffd5" +
    "\022\uffd5\042\uffd5\044\uffd5\045\uffd5\046\uffd5\051\uffd5\052" +
    "\uffd5\054\uffd5\055\uffd5\060\uffd5\001\002\000\004\004\250" +
    "\001\002\000\004\062\251\001\002\000\004\065\252\001" +
    "\002\000\042\004\ufff0\005\ufff0\006\ufff0\007\ufff0\010\ufff0" +
    "\011\ufff0\022\ufff0\042\ufff0\044\ufff0\045\ufff0\046\ufff0\051" +
    "\ufff0\052\ufff0\054\ufff0\055\ufff0\060\ufff0\001\002\000\052" +
    "\002\ufff8\004\ufff8\005\ufff8\006\ufff8\007\ufff8\010\ufff8\011" +
    "\ufff8\022\ufff8\042\ufff8\043\ufff8\044\ufff8\045\ufff8\046\ufff8" +
    "\047\ufff8\051\ufff8\052\ufff8\054\ufff8\055\ufff8\056\ufff8\060" +
    "\ufff8\001\002\000\006\062\uffdc\066\uffdc\001\002\000\010" +
    "\002\ufff9\003\126\057\130\001\002\000\016\005\ufffe\006" +
    "\ufffe\007\ufffe\010\ufffe\011\ufffe\056\ufffe\001\002\000\004" +
    "\002\000\001\002\000\004\002\uffff\001\002\000\004\002" +
    "\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\257\000\016\002\003\003\010\004\013\010\012\013" +
    "\014\024\006\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\005\257\001" +
    "\001\000\012\004\255\010\012\013\014\024\006\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\011\022\001\001\000\012\013\117\025\120\026\121\027" +
    "\116\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\030\027\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\030\107\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\030\104\001\001" +
    "\000\002\001\001\000\004\030\103\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\030\045\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\030\102\001\001\000" +
    "\004\030\101\001\001\000\004\030\100\001\001\000\004" +
    "\030\077\001\001\000\004\030\076\001\001\000\004\030" +
    "\075\001\001\000\004\030\074\001\001\000\004\030\073" +
    "\001\001\000\004\030\072\001\001\000\004\030\071\001" +
    "\001\000\004\030\070\001\001\000\004\030\067\001\001" +
    "\000\004\030\066\001\001\000\004\030\065\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\006\013\117\027\123\001\001\000\002\001" +
    "\001\000\004\005\126\001\001\000\002\001\001\000\002" +
    "\001\001\000\026\006\134\007\144\010\143\012\140\013" +
    "\141\014\145\015\142\016\131\017\150\020\130\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\024\007\241\010\143\012\140\013\141" +
    "\014\145\015\142\016\131\017\150\020\130\001\001\000" +
    "\004\030\236\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\012\156\001\001\000\002\001\001\000\004\030" +
    "\160\001\001\000\002\001\001\000\004\030\162\001\001" +
    "\000\002\001\001\000\004\005\164\001\001\000\002\001" +
    "\001\000\004\030\171\001\001\000\004\030\167\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\030\174\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\030\177\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\011\022\001\001\000\004\030" +
    "\206\001\001\000\002\001\001\000\004\005\210\001\001" +
    "\000\002\001\001\000\004\005\212\001\001\000\002\001" +
    "\001\000\004\030\214\001\001\000\002\001\001\000\002" +
    "\001\001\000\010\021\222\022\221\023\220\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\022\233\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\005\227\001\001\000\002\001\001" +
    "\000\004\005\231\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\005\235\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\030\243\001\001\000\002" +
    "\001\001\000\004\005\245\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\005" +
    "\256\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


  /** Scan to get the next Symbol. */
  public java_cup.runtime.Symbol scan()
    throws java.lang.Exception
    {

    return s.next_token();

    }


    private Lexer s;
    public Parser(Lexer s) { this.s = s; }

    @Override
    public void syntax_error(Symbol sym) {
        System.err.println("Error de sintaxis en línea "
                           + (sym.left + 1) + ", columna " + (sym.right + 1));
        System.err.println("Token inesperado: " + sym.value);
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$Parser$actions {
  private final Parser parser;

  /** Constructor */
  CUP$Parser$actions(Parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action_part00000000(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Parser$result;

      /* select the action based on the action number */
      switch (CUP$Parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= programa EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		RESULT = start_val;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Parser$parser.done_parsing();
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // programa ::= declaracionesGlobales MAIN bloque 
            {
              Object RESULT =null;
		 System.out.println("Regla 'programa' con declaracionesGlobales + MAIN"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // programa ::= MAIN bloque 
            {
              Object RESULT =null;
		 System.out.println("Regla 'programa' con sólo MAIN"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // declaracionesGlobales ::= declaracionesGlobales globalDeclaracion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("declaracionesGlobales",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // declaracionesGlobales ::= globalDeclaracion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("declaracionesGlobales",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // globalDeclaracion ::= declaracion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("globalDeclaracion",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // globalDeclaracion ::= funcion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("globalDeclaracion",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // bloque ::= ABRECUENTO lista_sentencias CIERRACUENTO 
            {
              Object RESULT =null;
		 System.out.println("Regla 'bloque' ejecutada."); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("bloque",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // bloque ::= 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("bloque",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // bloque ::= error CIERRACUENTO 
            {
              Object RESULT =null;
		
      System.err.println("Error en bloque. Se ignoraron tokens hasta '}'.");
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("bloque",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // lista_sentencias ::= lista_sentencias sentencia 
            {
              Object RESULT =null;
		 System.out.println("Regla 'lista_sentencias' procesando lista."); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_sentencias",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // lista_sentencias ::= sentencia 
            {
              Object RESULT =null;
		 System.out.println("Regla 'lista_sentencias' procesando sentencia."); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_sentencias",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // lista_sentencias ::= error PUNTO_Y_COMA 
            {
              Object RESULT =null;
		
      System.err.println("Error en lista de sentencias. Se ignoraron tokens hasta ';'.");
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_sentencias",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // sentencia ::= declaracion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // sentencia ::= asignacion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // sentencia ::= control_estructuras 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // sentencia ::= PRINT ABREREGALO expresion CIERRAREGALO PUNTO_Y_COMA 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		
         System.out.println("Imprimiendo la expresión: " + (String)e);
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // sentencia ::= READ ABREREGALO IDENTIFICADOR CIERRAREGALO PUNTO_Y_COMA 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		
         System.out.println("Leyendo a variable: " + id);
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // sentencia ::= RETURN expresion PUNTO_Y_COMA 
            {
              Object RESULT =null;
		int retleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int retright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Object ret = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
         System.out.println("Return con expr: " + (String)ret);
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // sentencia ::= BREAK PUNTO_Y_COMA 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // sentencia ::= UNKNOWN_TOKEN 
            {
              Object RESULT =null;
		int unkleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int unkright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object unk = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
         System.err.println("Sentencia desconocida: se ignora token " + unk);
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // declaracion ::= tipo_dato IDENTIFICADOR declaracion_aux 
            {
              Object RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object t = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int auxleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int auxright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object aux = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
      System.out.println("Declaración detectada:");
      System.out.println("- Tipo de dato: " + (String)t);
      System.out.println("- Variable: " + id);
      System.out.println("- Inicialización: " + (aux != null? aux : "Ninguna"));
      RESULT = null;
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("declaracion",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // declaracion_aux ::= PUNTO_Y_COMA 
            {
              Object RESULT =null;
		
       RESULT = null;
     
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("declaracion_aux",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // declaracion_aux ::= ASIGNA expresion PUNTO_Y_COMA 
            {
              Object RESULT =null;
		int exleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int exright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Object ex = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
       RESULT = " = " + ex;
     
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("declaracion_aux",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // declaracion_aux ::= ABREEMPAQUE L_INTEGER CIERRAEMPAQUE PUNTO_Y_COMA 
            {
              Object RESULT =null;
		int litleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int litright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object lit = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		
       RESULT = "[ " + lit + " ]";
     
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("declaracion_aux",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // tipo_dato ::= INTEGER 
            {
              Object RESULT =null;
		 RESULT = "int";   
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("tipo_dato",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // tipo_dato ::= FLOAT 
            {
              Object RESULT =null;
		 RESULT = "float"; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("tipo_dato",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // tipo_dato ::= BOOL 
            {
              Object RESULT =null;
		 RESULT = "bool";  
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("tipo_dato",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // tipo_dato ::= CHAR 
            {
              Object RESULT =null;
		 RESULT = "char";  
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("tipo_dato",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // tipo_dato ::= STRING 
            {
              Object RESULT =null;
		 RESULT = "string";
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("tipo_dato",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // asignacion ::= IDENTIFICADOR ASIGNA expresion PUNTO_Y_COMA 
            {
              Object RESULT =null;
		int idVarleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int idVarright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		Object idVar = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int exleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int exright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Object ex = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
        System.out.println("Asignación simple a variable " + idVar
                           + " con expr: " + ex);
        RESULT = "assign(" + idVar + "=" + ex + ")";
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("asignacion",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // asignacion ::= IDENTIFICADOR ABREEMPAQUE expresion CIERRAEMPAQUE ASIGNA expresion PUNTO_Y_COMA 
            {
              Object RESULT =null;
		int idVarleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)).left;
		int idVarright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)).right;
		Object idVar = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-6)).value;
		int posleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).left;
		int posright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).right;
		Object pos = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-4)).value;
		int rhsleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int rhsright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Object rhs = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
        System.out.println("Asignación a arreglo " + idVar
                           + "[" + pos + "] = " + rhs);
        RESULT = "assignArr(" + idVar + "["+pos+"]="+rhs+")";
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("asignacion",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // funcion ::= tipo_dato IDENTIFICADOR ABREREGALO parametros CIERRAREGALO bloque 
            {
              Object RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).right;
		Object t = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-5)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-4)).value;
		int pleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int pright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object p = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object b = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
       System.out.println("Función declarada: " + id + " de tipo " + t
                          + ", con params: " + (p != null ? p : "0 params")
                          + " y un bloque.");
       RESULT = "func["+t+" "+id+"("+p+")]";
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("funcion",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // parametros ::= 
            {
              Object RESULT =null;
		 RESULT = ""; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("parametros",19, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // parametros ::= lista_parametros 
            {
              Object RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int pright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object p = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = p; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("parametros",19, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // lista_parametros ::= param_dec 
            {
              Object RESULT =null;
		int pdleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int pdright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object pd = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        RESULT = pd;
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_parametros",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // lista_parametros ::= lista_parametros COMA param_dec 
            {
              Object RESULT =null;
		int lpleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int lpright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object lp = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int pdleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int pdright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object pd = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        RESULT = (String)lp + ", " + (String)pd;
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_parametros",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // param_dec ::= tipo_dato IDENTIFICADOR 
            {
              Object RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Object t = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
         String paramStr = t + " " + id;
         RESULT = paramStr;
         System.out.println("Parametro: " + paramStr);
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("param_dec",21, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // control_estructuras ::= if_estructura 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("control_estructuras",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // control_estructuras ::= while_estructura 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("control_estructuras",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // control_estructuras ::= for_estructura 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("control_estructuras",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // control_estructuras ::= switch_estructura 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("control_estructuras",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // if_estructura ::= IF ABREREGALO expresion CIERRAREGALO bloque 
            {
              Object RESULT =null;
		int condleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int condright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object cond = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object b = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        RESULT = "if("+cond+")"+b;
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("if_estructura",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // if_estructura ::= IF ABREREGALO expresion CIERRAREGALO bloque ELSE bloque 
            {
              Object RESULT =null;
		int condleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).left;
		int condright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).right;
		Object cond = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-4)).value;
		int b1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int b1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object b1 = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int b2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int b2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object b2 = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        RESULT = "if("+cond+")"+b1+" else "+b2;
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("if_estructura",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // while_estructura ::= WHILE ABREREGALO expresion CIERRAREGALO bloque 
            {
              Object RESULT =null;
		int condleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int condright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object cond = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int blleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int blright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object bl = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        RESULT = "while("+cond+")"+bl;
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("while_estructura",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // for_estructura ::= FOR ABREREGALO asignacion COMA expresion COMA expresion CIERRAREGALO bloque 
            {
              Object RESULT =null;
		int inileft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)).left;
		int iniright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)).right;
		Object ini = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-6)).value;
		int condleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).left;
		int condright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).right;
		Object cond = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-4)).value;
		int stepleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int stepright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object step = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int blleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int blright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object bl = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        RESULT = "for("+ini+", "+cond+", "+step+")"+bl;
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("for_estructura",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-8)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // switch_estructura ::= SWITCH ABREREGALO expresion CIERRAREGALO ABRECUENTO case_blocks CIERRACUENTO 
            {
              Object RESULT =null;
		int swleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).left;
		int swright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).right;
		Object sw = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-4)).value;
		int csleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int csright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Object cs = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
        RESULT = "switch("+sw+") { "+cs+" }";
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("switch_estructura",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // case_blocks ::= case_blocks case_block 
            {
              Object RESULT =null;
		int prevleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int prevright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Object prev = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int cbleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int cbright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object cb = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        RESULT = prev + " " + cb;
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("case_blocks",15, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // case_blocks ::= case_block 
            {
              Object RESULT =null;
		int cbleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int cbright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object cb = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        RESULT = cb;
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("case_blocks",15, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // case_blocks ::= default_block 
            {
              Object RESULT =null;
		int dbleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int dbright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object db = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        RESULT = db;
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("case_blocks",15, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // case_block ::= CASE L_INTEGER DOS_PUNTOS bloque 
            {
              Object RESULT =null;
		int lileft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int liright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object li = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int blleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int blright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object bl = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        RESULT = "case "+li+": "+bl;
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("case_block",16, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // case_block ::= CASE CHAR_LITERAL DOS_PUNTOS bloque 
            {
              Object RESULT =null;
		int chleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int chright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object ch = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int blleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int blright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object bl = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        RESULT = "case '"+ch+"': "+bl;
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("case_block",16, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // default_block ::= DEFAULT DOS_PUNTOS bloque 
            {
              Object RESULT =null;
		int blleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int blright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object bl = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        RESULT = "default: "+bl;
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("default_block",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // expresion ::= expresion DISYUNCION expresion 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
          RESULT = "("+e1+" || "+e2+")";
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // expresion ::= expresion CONJUNCION expresion 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
          RESULT = "("+e1+" && "+e2+")";
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // expresion ::= expresion IGUALDAD expresion 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
          RESULT = "("+e1+" == "+e2+")";
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // expresion ::= expresion DIFERENTE expresion 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
          RESULT = "("+e1+" != "+e2+")";
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // expresion ::= expresion MENOR expresion 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
          RESULT = "("+e1+" < "+e2+")";
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // expresion ::= expresion MENOROIGUAL expresion 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
          RESULT = "("+e1+" <= "+e2+")";
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // expresion ::= expresion MAYOR expresion 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
          RESULT = "("+e1+" > "+e2+")";
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // expresion ::= expresion MAYOROIGUAL expresion 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
          RESULT = "("+e1+" >= "+e2+")";
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // expresion ::= expresion SUMA expresion 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
          RESULT = "("+e1+" + "+e2+")";
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // expresion ::= expresion RESTA expresion 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
          RESULT = "("+e1+" - "+e2+")";
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // expresion ::= expresion MULTIPLICACION expresion 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
          RESULT = "("+e1+" * "+e2+")";
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // expresion ::= expresion DIVISION expresion 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
          RESULT = "("+e1+" / "+e2+")";
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // expresion ::= expresion MODULE expresion 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
          RESULT = "("+e1+" % "+e2+")";
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // expresion ::= expresion POTENCIA expresion 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
          RESULT = "("+e1+" ^ "+e2+")";
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // expresion ::= NEGACION expresion 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
          RESULT = "!"+e;
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // expresion ::= RESTA expresion 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
          RESULT = "-"+e;
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // expresion ::= INCREMENTO IDENTIFICADOR 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
          RESULT = "++"+id;
          System.out.println("Expresión: ++" + id);
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // expresion ::= DECREMENTO IDENTIFICADOR 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
          RESULT = "--"+id;
          System.out.println("Expresión: --" + id);
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 71: // expresion ::= IDENTIFICADOR INCREMENTO 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
          RESULT = id + "++";
          System.out.println("Expresión: " + id + "++");
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 72: // expresion ::= IDENTIFICADOR DECREMENTO 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
          RESULT = id + "--";
          System.out.println("Expresión: " + id + "--");
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 73: // expresion ::= IDENTIFICADOR 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
          RESULT = id;
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 74: // expresion ::= L_INTEGER 
            {
              Object RESULT =null;
		int lintleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int lintright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object lint = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
          RESULT = lint.toString();
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 75: // expresion ::= FLOAT_LITERAL 
            {
              Object RESULT =null;
		int flileft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int fliright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object fli = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
          RESULT = fli.toString();
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 76: // expresion ::= CHAR_LITERAL 
            {
              Object RESULT =null;
		int chlleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int chlright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object chl = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
          RESULT = "'"+chl+"'";
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 77: // expresion ::= STRING_LITERAL 
            {
              Object RESULT =null;
		int strleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int strright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object str = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
          RESULT = "\""+str+"\"";
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 78: // expresion ::= BOOL_LITERAL 
            {
              Object RESULT =null;
		int booleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int booright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object boo = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
          RESULT = boo.toString();
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 79: // expresion ::= IDENTIFICADOR ABREEMPAQUE expresion CIERRAEMPAQUE 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int exleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int exright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Object ex = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
          RESULT = id + "["+ex+"]";
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 80: // expresion ::= ABREREGALO expresion CIERRAREGALO 
            {
              Object RESULT =null;
		int exleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int exright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Object ex = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
          RESULT = "("+ex+")";
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 81: // expresion ::= error CIERRAREGALO 
            {
              Object RESULT =null;
		
        System.err.println("Error en expresión. Se ignoraron tokens hasta ')'.");
        RESULT = null;
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$Parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
              return CUP$Parser$do_action_part00000000(
                               CUP$Parser$act_num,
                               CUP$Parser$parser,
                               CUP$Parser$stack,
                               CUP$Parser$top);
    }
}

}
